---
title: "Fecal results"
author: "Juliana Balluffi-Fry"
date: "2025-02-28"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("Scripts/09-fecal_results.R")


```

Fecal samples from control hares had an average of `r fecal[food == "Control", round(mean(CP_dm, na.rm = TRUE), 2)]` ± `r fecal[food == "Control", round(sd(CP_dm), 2)]`% protein, `r round(fecal[food == "Suppl.", mean(CP_dm, na.rm = TRUE)] - fecal[food == "Control", median(CP_dm)], 2)`% less than samples from food supplemented hares (p = `r pfood`, t = `r tfood`, df = `r dffood`, R2 = `r round(rsq(foodmod), 2)`; Figure 2B). Fecal samples collected in January were `r round(fecal[m == 1, median(CP_dm)] - fecal[m == 3, median(CP_dm)], 2)`% higher in protein than those collected in March (p = `r pfec`, t = `r tfec`, df = `r dffec`, R2 = `r round(rsq(fecmod), 2)`). Using the `r fecfor[, .N]` cases where fecal samples were collected from a hare with weekly foraging data, fecal protein showed a slightly negative response to foraging effort (p = `r pfecfor`, t = `r tfecfor`, df = `r dffecfor`, R2 = `r fecforR2`).

The most parsimonious models for explaining diet quality, or fecal protein content, were models D2 and D4, which contained twig biomass and temperature (R2 = `r round(rsq(D2), 2)`), and hare density and temperature (R2 = `r round(rsq(D4), 2)`), respectively (Table 2). Model D2 found that as twig availability increased from `r biopred[, min(x)]` to `r biopred[, max(x)]` kg/ha, fecal protein increased from `r biopred[x == min(x), round(mean(predicted), 1)]`% to `r biopred[x == max(x), round(mean(predicted), 1)]`% (p = `r sb_p`, β = `r sb_coef` ± `r sb_se` ; Figure 5A). While fecal samples from food supplemented had `r food_coef` ± `r food_se`% higher protein than controls across the range of twig availability, there was no difference between the two groups' responses to twig biomass (p = `r foodsb_p`; Figure 5A). There was a significant interaction between food treatment and ambient temperature (p = `r foodtemp_p`). As weekly temperatures increased from `r min(temppred$x)` to `r max(temppred$x)`°C, food supplemented hares increased their fecal protein by `r round(temppred[food == 1 & x == max(x), predicted] - temppred[food == 1 & x == min(x), predicted], 2)`%, always staying above the 10% threshold, while control hare fecal protein decreased  by `r abs(round(temppred[food == 0 & x == max(x), predicted] - temppred[food == 0 & x == min(x), predicted], 2))`%, from `r round(temppred[food == 0 & x == min(x), predicted], 2)`% to `r round(temppred[food == 0 & x == max(x), predicted], 2)`% (Figure 5B). Model D4 showed that hare fecal protein content decreased slightly as hare density increased, about `r abs(dens_coef/2)` ± `r dens_se/2` for every 0.5 hare/ha increase. As the hare population increased from `r denspred[, min(x)]` to `r denspred[, max(x)]` hares/ha, fecal protein decreased from `r denspred[x == min(x), round(mean(predicted), 1)]`% to `r denspred[x == max(x), round(mean(predicted), 1)]`%, and food treatment did not affect the slope of this response (p = `r fooddens_p`; Figure 5C).


