---
title: "Foraging results"
author: "Juliana Balluffi-Fry"
date: "27/02/2025"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("Scripts/08-foraging_results.R")

```

Averaged by week, individual snowshoe hare foraging rates varied greatly, ranging from  `r forag[, round(min(forage), 1)]` to `r forag[, round(max(forage), 1)]` hours per day (`r forag[, round(mean(forage), 1)]` ± `r forag[, round(sd(forage), 1)]`). Food supplementation reduced foraging effort by `r round(foragfood[food == "Control", mean(forage)] - foragfood[food == "Suppl.", mean(forage)], 1)` hours (p = `r supp_p`, t = `r supp_t`, df = `r supp_df`, R2 = `r round(rsq(suppmod), 3) `; Figure 2A). As daylight hours became longer from January to March, hares decreased their foraging rate by `r nightcoef` ± `r nightse` minutes per hour decrease in night length (p = `r pnight`, t = `r tnight`, df = `r dfnight`, R2 = `r round(rsq(nightmod), 3)`).

The most parsimonious model for explaining foraging effort by control hares (delta AIC < 2) was that which included twig biomass and temperature as fixed effects (Table 1, model D2). This model found that hares foraged `r sb_coef*10*60` ± `r sb_se*10*60` minutes more per day for every 10 kg per hectare increase in available twig biomass (t = `r sb_t`, β = `r sb_coef` ± `r sb_se`, CI = ). This meant that as twig biomass increased from `r sb_pred[, min(x)]` to `r sb_pred[, max(x)]` kg/ha, hares foraging effort increased from `r sb_pred[x == min(x), round(predicted, 1)]` to `r sb_pred[x == max(x), round(predicted, 1)]` hr/day (Figure 3A). Additionally, the same model showed that for every 10 °C increase in ambient temperature, hares foraged `r t_coef*10*60` ± `r t_se*10*60` minutes more per day (t = `r t_t`, β = `r t_coef` ± `r t_se`, CI = ). Meaning that as weekly temperatures increased from the coldest of `r t_pred[, min(x)]` °C to the warmest of `r t_pred[, max(x)]` °C, hare foraging rate increased from `r t_pred[x == min(x), round(predicted, 1)]` to `r t_pred[x == max(x), round(predicted, 1)]` hours per day (Figure 3B). While temperature and biomass explained a lot of variance within the model (Marginal R2 = `r D2MR2`), more variance was explained by individual differences (Conditional R2 - Marginal R2 = `r (D2CR2 - D2MR2)`).


After testing this model (D2) on the food treatment data set, we found no effect of available twig biomass overall (t = `r foodsb_t`), but there was a interaction between food treatment and twig biomass on foraging rates (β = `r foodsbf_coef` ± `r foodsbf_se`, t = `r intsb_t`, CI = ). When twigs were least available (`r foodb_pred[, min(x)]` kg/ha), foraging rates were similar between control and food supplemented individuals, but when twigs were most available (`r foodb_pred[, max(x)]` kg/ha), controls foraged `r round(foodb_pred[food == 0 & x == max(x), predicted] - foodb_pred[food == 1 & x == max(x), predicted], 2)` hours more than food supplemented individuals (Figure 3C). Similar to the control model, this model showed foraging effort increased with warmer temperatures (β = `r foodt_coef*10*60` ± `r foodt_se*10*60`, t = `r foodt_t`, CI = ). There was also a significant interaction between food treatment and temperature (β = `r foodtf_coef` ± `r foodtf_se`, t = `r intt_t`); control and food supplemented hares foraged for similar lengths of time at the coldest temperatures, but during the warmest weeks, as both groups foraged more, control hares foraged `r round(foodt_pred[x == max(x) & food == "Control", predicted] - foodt_pred[x == max(x) & food == "Suppl.", predicted], 1)` hours more per day than food supplemented hares (Figure 3D).



