---
title: "Descriptive Results"
author: "Juliana Balluffi-Fry"
date: "2025-02-25"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)

dat <- readRDS("Output/Data/full_data_weekly_nogrid.rds")
fecal <- readRDS("Output/Data/fecal_protein.rds")
forag <- readRDS("Output/Data/foraging_weekly.rds")

#get controls only
foragcon <- forag[food == 0]

#take only the years where there was food add
foodyears <- forag[food == 1, unique(winter)]

#take only females for food add comparisons
foragfood <- forag[winter %in% foodyears]

#effect of food on food add dataset
foodmod <- anova(lm(forage ~ food, foragfood))
pfood <- round(foodmod$`Pr(>F)`[1], 3)

#effect of sex on controls
sexmod <- anova(lm(forage ~ sex, foragcon))
psex <- round(sexmod$`Pr(>F)`[1], 3)

#effect of night length on foraging rate
nightmod <- lm(forage ~ nightlength, forag) #make model
nightsum <- summary(nightmod) #sum of model
nightanova <- anova(nightmod) #anova of model
nightcoef <- round(nightsum$coefficients[, 1][2]*60, 2) #coefficient
nightse <- round(nightsum$coefficients[, 2][2]*60, 2) #standard error
pnight <- round(nightanova$`Pr(>F)`[1], 3) #p-value

#effect of month on fecal protein
fecmod <- anova(lm(CP_dm ~ m, fecal)) #get anova
pfec <- round(fecmod$`Pr(>F)`[1], 3) #pull p value

#get avg fecal by week. only a few cases that had multiple fecal in 1 week
fecal2 <- fecal[, .(CP = mean(CP_dm)), by = .(id, year, week)]

#merge shortened fecal with foraging rates
fecfor <- merge(forag, fecal2, by = c("id", "year", "week"))

#slight negative correlation between weekly foraging rate and fecal protein
fecformod <- lm(CP ~ forage, fecfor)
fecforanova <- anova(fecformod)
fecforp <- round(fecforanova$`Pr(>F)`[1], 3)
fecforslope <- round(fecformod$coefficients[2], 2)



```



##General results

Snowshoe hare densities decreased over each winter, because they were always predated, with the greatest overwinter declines occurring from 2016 to 2018, after which hare densities were mostly below the median of `r dat[, round(median(haredensity), 2)]` ± `r dat[, round(sd(haredensity), 2)]` hares per hectare (Figure 1A). Over our study period, hares experienced a `r dat[, round(median(mortrate), 2)]` ± `r dat[, round(sd(mortrate), 2)]`% chance of being predated, with 2020 showing the highest mortality rate (`r dat[year == 2020, round(median(mortrate), 2)]`%) and 2017 showing the lowest (`r dat[year == 2017, round(median(mortrate), 2)]`%; Figure 1B). The median daily temperature across all years was `r dat[, round(median(temp), 2)]` ± `r dat[, round(sd(temp), 2)]` C (Figure 1C). Temperatures fluctuated week to week, going above and below the median temperature, except during 2016 when all weeks were warmer than the median (Figure 1C). The median snow depth across all winters was `r dat[, round(median(snow), 2)]` ± `r dat[, round(sd(snow), 2)]` cm. Snow increased over every winter, reaching a maximum of `r dat[, round(max(snow), 2)]` cm in 2021. The pattern of accumulation differed between winters; some winters experienced gradual increases (e.g., 2018 and 2019) while others experienced dramatic increases over short periods of time (e.g., 2017 and 2020; Figure 2D). In 2016 and 2019, when temperatures were relatively warmer, snow began to melt and decline in march. Snow depth correlated with available willow twig biomass. We estimated a median of `r dat[, round(median(biomass), 2)]` ± `r dat[, round(sd(biomass), 2)]` kg per hectare of soluble willow twigs available to hares (Figure 1D).


Averaged by week, snowshoe hare foraging rate was very flexible (`r forag[, round(median(forage), 2)]` ± `r forag[, round(sd(forage), 2)]`), ranging from a minimum of `r forag[, round(min(forage), 2)]` to `r forag[, round(max(forage), 2)]` hours per day (Figure 2A). Food supplementation reduced female foraging effort by `r round(foragfood[food == 0, mean(forage)] - foragfood[food == 1, mean(forage)], 2)` hours (p = `r pfood`; Figure 2A). As day length increased over winter from January to March, hares decreased their foraging rate by `r nightcoef` ± `r nightse` minutes per hour decrease in night length (p = `r pnight`). The median protein composition of fecal sample from food supplemented and control individuals were `r fecal[food == 1, round(median(CP_dm), 2)]` ± `r fecal[food == 1, round(sd(CP_dm), 2)]`% and `r fecal[food == 0, round(median(CP_dm), 2)]` ± `r fecal[food == 0, round(sd(CP_dm), 2)]`%, respectively (Figure 2B). Fecal samples collected in January were higher in protein (`r fecal[m == 1, round(median(CP_dm), 2)]`%) than those collected in March (`r fecal[m == 3, round(median(CP_dm), 2)]`%; p = `r pfec`). Using the `r fecfor[, .N]` cases where fecal samples were collected from a hare with weekly foraging data, fecal protein showed a slight positive response to foraging effort (b = `r fecforslope`, p = `r fecforp`).

